= Rust for Safety
:icons: font
:lecture: References & Borrowing
:table-caption!:
:example-caption!:

[.centered]
== What you can own, you can borrow

Ownership provides a solid semantic base, but is for values.  Reuse of data after a function call is not possible with ownership if the called function doesn't return the ownership to the value again.

[.two-col]
== References

[source,rust]
----
#[derive(Debug)]
struct Point {
    x: i32,
    y: i32 
}

fn main() {
    let mut p = Point { x: 1, y: 2 }; <1>
    inspect(&p); <3>
    p.x = 2; <4>
    inspect(&p);
    <5>
}

fn inspect(p: &Point) { <2>
    println!("{:?}", p);
}
----

--

<1> Just a normal stack allocation
<2> `inspect` takes a reference using `&` instead of a bare value
<3> The call to `inspect` also needs a `&` to reference the stack value
<4> In between the two calls, we can modify the value
<5> Deallocation point

--

[.centered]
== Immutable references

`&` is the so-called "immutable" reference. They are:

* Available multiple times
* Always valid (always pointing to living data)
* Never `null`
* Guaranteed to never observe mutation of the pointed value

[.two-col]
== Modifying immutable references

[source,rust]
----
fn main() {
    let mut point = Point { x: 1, y: 2 };
    let ref = &point; // -\ <1>
    point.x = 2;      //  | <2>
    inspect(ref);     // -/ <3>
}
----

--

<1> reference is taken here.
<2> mutation happens here.
<3> because the reference is still alive, it would observe mutation

--

== Error

[source,rust]
----
error[E0506]: cannot assign to `point.x` because it is borrowed
  --> scratch.rs:10:5
   |
9  |     let reference = &point;
   |                     ------ borrow of `point.x` occurs here
10 |     point.x = 2;
   |     ^^^^^^^^^^^ assignment to borrowed `point.x` occurs here
11 |     inspect(reference);
   |             --------- borrow later used here

error: aborting due to previous error
----

[.centered]
== Lingo

Immutable references _borrow immutably_.

[.two-col]
== Mutation

[source,rust]
----
fn main() {
    let mut p = Point { x: 1, y: 2 };
    inspect(&p); <4>
    move_point(&mut p,3,3); <3>
    inspect(&p); <4>
}

fn move_point(
    p: &mut Point, <1> <2>
    x: i32, y: i32
) {
    p.x = x;
    p.y = y;
}
----

--

<1> Instead ot `&`, use `&mut` to _mutably borrow_.
<2> Mutable borrows are unique at any time in the program!
<3> Use `&mut` at the call site. This requires a mutable value!
<4> Immutable borrows still cannot observe mutation.

--

[.centered]
== The Borrowing Rules

Values can be:

* Borrowed immutably as often as you'd like
* Or mutably exactly once
* The two rules are mutually exclusive.

Rust forbids _shared mutability_.

[.centered]
== What does that save us from?

[source,rust]
----
fn push_all(on: &mut Vec<u8>, from: &Vec<u8>) {

}
----

== Dereferencing

[source,rust]
----
fn main() {
    let number: &mut i32 = &mut 4;
    *number = 10;
    println!("{}", number);
}
----

[.two-col]
== Other kinds of borrows

[source,rust]
----
struct ExampleIter<'iter, T> { <2>
    vec: &'iter Vec<T>, <1>
    pos: usize,
}

fn main() {
    let vec: Vec<u32> = vec![1,2,3]; <4>
    let iter: Iter<'_, u32> = vec.iter(); <3> <4>
    for i in iter {
        println!("{}", i);
    }
}
----

--

<1> Iterators carry an inner refernce to what they _iterate over_. They are invalid if that went away.
<2> Therefore, they carry a _lifetime_, to bind them to the value.
<3> Iterators are gained from what they iterate over.
<4> Both `Vec` and `Iter` are owned values!

--

== Lingo

This iterators _borrows_ the `Vec` it iterators over.


[.two-col]
== Let's try to break it!

[source, rust]
----
fn main() {
    let vec = vec![1,2,3];
    let iter = vec.iter(); <1>
    drop(vec); <2>
    for i in iter { <3>
        println!("{}", i);
    }
}
----

--

<1> creates an iterator over a vector.
<2> forcibly deallocates the vector.
<3> tries to iterate and would iterate over deallocated memory

--

[.centered]
== Or, as `rustc` would say...

[source,text]
----
error[E0505]: cannot move out of `vec` because it is borrowed
  --> scratch.rs:11:10
   |
10 |     let iter: Iter<'_, u32> = vec.iter();
   |                               --- borrow of `vec` occurs here
11 |     drop(vec);
   |          ^^^ move out of `vec` occurs here
12 |     for i in iter {
   |              ---- borrow later used her
----

[.centered]
== Summary

* The borrowing rules keep references safe
* They apply to values with inner references and references alike!
* Inner referencing behaviour is always appearant from the type signature
* _Owners_ decide about the time values are in memory
* Rust does _never_ reorder your code. It only points at its flaws.
